// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.
// Generation checksum: 9f97c73bb7d47eac293be1d2e6543aad648e04ae15140b842b61ab80aad75253

package blacklist

import (
	"context"
	"strings"

	"gorm.io/cli/gorm/typed"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func I1[T any](db *gorm.DB, opts ...clause.Expression) _I1Interface[T] {
	return _I1Impl[T]{
		Interface: typed.G[T](db, opts...),
	}
}

type _I1Interface[T any] interface {
	typed.Interface[T]
	ByID(ctx context.Context, id int) (T, error)
}

type _I1Impl[T any] struct {
	typed.Interface[T]
}

func (e _I1Impl[T]) ByID(ctx context.Context, id int) (T, error) {
	var sb strings.Builder
	_params := make([]any, 0, 2)

	sb.WriteString("SELECT * FROM ? WHERE id=?")
	_params = append(_params, clause.Table{Name: clause.CurrentTable}, id)

	var result T
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}
