// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.
// Generation checksum: 0f105200a37c8f33624dcb5e1785fec99298918d3c8f1410136b8ec90382bb71

package blacklist

import (
	"gorm.io/cli/gorm/examples/filters/blacklist"
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm/clause"
)

func newS1StructRelation(prefix string, depth int) field.Struct[blacklist.S1] {
	return field.Struct[blacklist.S1]{}.WithName(prefix)
}

func newS1SliceRelation(prefix string, depth int) field.Slice[blacklist.S1] {
	return field.Slice[blacklist.S1]{}.WithName(prefix)
}

type genS1 struct {
	ID   field.Number[int]
	Name field.String
}

func (g genS1) WithTable(table string) genS1 {
	return genS1{
		ID:   field.Number[int]{}.WithColumn("id").WithTable(table),
		Name: field.String{}.WithColumn("name").WithTable(table),
	}
}

var S1 = genS1{}.WithTable(clause.CurrentTable)
