package generator

var (
	codeGenHint = "// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT."
	pkgTmpl     = codeGenHint + `
// Generation checksum: {{.GenerationChecksum}}

package {{.ToPackage}}

import (
    {{- if (and (.HasAnyRelations) (.UsedRelations)) }}
    "strings"
    {{- end }}
    "gorm.io/gorm"
    "gorm.io/gorm/clause"
    "gorm.io/cli/gorm/field"
    {{- if .UsedTypedAPI }}
    "gorm.io/cli/gorm/typed"
    {{- end }}
    {{range .Imports -}}
    {{.ImportPath}}
    {{end -}}
)

{{range .Interfaces}}
{{$IfaceName := .IfaceName}}
func {{.Name}}[T any](db *gorm.DB, opts ...clause.Expression) {{$IfaceName}}Interface[T] {
    return {{$IfaceName}}Impl[T]{
        Interface: {{if $.UsedTypedAPI}}typed{{else}}gorm{{end}}.G[T](db, opts...),
    }
}

type {{$IfaceName}}Interface[T any] interface {
    {{if $.UsedTypedAPI}}typed{{else}}gorm{{end}}.Interface[T]
    {{range .Methods -}}
    {{.Name}}({{.ParamsString}}) ({{.ResultString}})
    {{end}}
}

type {{$IfaceName}}Impl[T any] struct {
    {{if $.UsedTypedAPI}}typed{{else}}gorm{{end}}.Interface[T]
}

{{range .Methods}}
func (e {{$IfaceName}}Impl[T]) {{.Name}}({{.ParamsString}}) ({{.ResultString}}) {
	{{.Body}}
}
{{end}}
{{end}}

{{range .Structs}}
{{- if .UsedRelations}}
{{if .HasRelationFields}}
type {{.RelationsFieldsTypeName}}{{.TypeParamsSuffix}} struct {
	{{range .RelationFields -}}
	{{.Name}} {{.TypeExpr}}
	{{end}}
}

type {{.StructRelationTypeName}}{{.TypeParamsSuffix}} struct {
	field.Struct[{{.QualifiedType $.Package}}]
	{{.RelationsFieldsTypeName}}{{.TypeArgsSuffix}}
}

type {{.SliceRelationTypeName}}{{.TypeParamsSuffix}} struct {
	field.Slice[{{.QualifiedType $.Package}}]
	{{.RelationsFieldsTypeName}}{{.TypeArgsSuffix}}
}

func {{.NewRelationsFieldsFuncName}}{{.TypeParamsSuffix}}(prefix string, depth int) {{.RelationsFieldsTypeName}}{{.TypeArgsSuffix}} {
	return {{.RelationsFieldsTypeName}}{{.TypeArgsSuffix}}{
		{{range .RelationFields -}}
		{{.Name}}: {{.InitExpr}},
		{{end -}}
	}
}

func {{.NewStructRelationFuncName}}{{.TypeParamsSuffix}}(prefix string, depth int) *{{.StructRelationTypeName}}{{.TypeArgsSuffix}} {
	rel := &{{.StructRelationTypeName}}{{.TypeArgsSuffix}}{
		field.Struct[{{.QualifiedType $.Package}}]{}.WithName(prefix),
		{{.RelationsFieldsTypeName}}{{.TypeArgsSuffix}}{},
	}
	if depth <= 0 {
		return rel
	}
	rel.{{.RelationsFieldsTypeName}} = {{.NewRelationsFieldsFuncName}}{{.TypeArgsSuffix}}(prefix, depth)
	return rel
}

func {{.NewSliceRelationFuncName}}{{.TypeParamsSuffix}}(prefix string, depth int) *{{.SliceRelationTypeName}}{{.TypeArgsSuffix}} {
	rel := &{{.SliceRelationTypeName}}{{.TypeArgsSuffix}}{
		field.Slice[{{.QualifiedType $.Package}}]{}.WithName(prefix),
		{{.RelationsFieldsTypeName}}{{.TypeArgsSuffix}}{},
	}
	if depth <= 0 {
		return rel
	}
	rel.{{.RelationsFieldsTypeName}} = {{.NewRelationsFieldsFuncName}}{{.TypeArgsSuffix}}(prefix, depth)
	return rel
}
{{else}}
func {{.NewStructRelationFuncName}}{{.TypeParamsSuffix}}(prefix string, depth int) field.Struct[{{.QualifiedType $.Package}}] {
	return field.Struct[{{.QualifiedType $.Package}}]{}.WithName(prefix)
}

func {{.NewSliceRelationFuncName}}{{.TypeParamsSuffix}}(prefix string, depth int) field.Slice[{{.QualifiedType $.Package}}] {
	return field.Slice[{{.QualifiedType $.Package}}]{}.WithName(prefix)
}
{{end}}

{{if .HasRelations}}
var {{.RelationsVarName}} = {{.NewRelationsFieldsFuncName}}("", {{$.MaxRelationDepth}})
{{end}}
{{end}}

type gen{{.Name}} struct {
	{{range .Fields -}}
	{{.Name}} {{.Type}}
	{{end}}
}

func (g gen{{.Name}}) WithTable(table string) gen{{.Name}} {
	return gen{{.Name}}{
		{{range .Fields -}}
		{{.Name}}: {{.Value}},
		{{end -}}
	}
}

var {{.Name}} = gen{{.Name}}{}.WithTable(clause.CurrentTable)
{{end}}
`
)
