// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package nested

import (
	"gorm.io/cli/gorm/examples/filters/twolevel/nested"
	"gorm.io/cli/gorm/field"
)

func newS1StructRelation(prefix string, depth int) field.Struct[nested.S1] {
	return field.Struct[nested.S1]{}.WithName(prefix)
}

func newS1SliceRelation(prefix string, depth int) field.Slice[nested.S1] {
	return field.Slice[nested.S1]{}.WithName(prefix)
}

var S1 = struct {
	ID field.Number[int]
}{
	ID: field.Number[int]{}.WithColumn("id"),
}
