// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.
// Generation checksum: e8137a0cbc478d9626b7de5311211eb31689d5c3eb699b3d9104aa0e5fb3b3d4

package nested

import (
	"gorm.io/cli/gorm/examples/filters/twolevel/nested"
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm/clause"
)

func newS1StructRelation(prefix string, depth int) field.Struct[nested.S1] {
	return field.Struct[nested.S1]{}.WithName(prefix)
}

func newS1SliceRelation(prefix string, depth int) field.Slice[nested.S1] {
	return field.Slice[nested.S1]{}.WithName(prefix)
}

type genS1 struct {
	ID field.Number[int]
}

func (g genS1) WithTable(table string) genS1 {
	return genS1{
		ID: field.Number[int]{}.WithColumn("id").WithTable(table),
	}
}

var S1 = genS1{}.WithTable(clause.CurrentTable)
