// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.
// Source checksum: 5c14b9a47f611caece744f80cf54d2208d9d55a50951c995b7c7570a1be4e210

package models

import (
	"strings"

	"gorm.io/cli/gorm/examples/models"
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm/clause"
)

type embeddedUserRelationsFields struct {
	Pets    *petSliceRelation
	Company field.Struct[models.Company]
}

type embeddedUserStructRelation struct {
	field.Struct[models.EmbeddedUser]
	embeddedUserRelationsFields
}

type embeddedUserSliceRelation struct {
	field.Slice[models.EmbeddedUser]
	embeddedUserRelationsFields
}

func newEmbeddedUserRelationsFields(prefix string, depth int) embeddedUserRelationsFields {
	return embeddedUserRelationsFields{
		Pets:    newPetSliceRelation(strings.TrimPrefix(prefix+".Pets", "."), depth-1),
		Company: newCompanyStructRelation(strings.TrimPrefix(prefix+".Company", "."), depth-1),
	}
}

func newEmbeddedUserStructRelation(prefix string, depth int) *embeddedUserStructRelation {
	rel := &embeddedUserStructRelation{
		field.Struct[models.EmbeddedUser]{}.WithName(prefix),
		embeddedUserRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.embeddedUserRelationsFields = newEmbeddedUserRelationsFields(prefix, depth)
	return rel
}

func newEmbeddedUserSliceRelation(prefix string, depth int) *embeddedUserSliceRelation {
	rel := &embeddedUserSliceRelation{
		field.Slice[models.EmbeddedUser]{}.WithName(prefix),
		embeddedUserRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.embeddedUserRelationsFields = newEmbeddedUserRelationsFields(prefix, depth)
	return rel
}

var EmbeddedUserRelations = newEmbeddedUserRelationsFields("", 4)

type genEmbeddedUser struct {
	Code    field.String
	Pets    field.Slice[models.Pet]
	Company field.Struct[models.Company]
	Name    field.String
}

func (g genEmbeddedUser) WithTable(table string) genEmbeddedUser {
	return genEmbeddedUser{
		Code:    field.String{}.WithColumn("code").WithTable(table),
		Pets:    field.Slice[models.Pet]{}.WithName("Pets"),
		Company: field.Struct[models.Company]{}.WithName("Company"),
		Name:    field.String{}.WithColumn("name").WithTable(table),
	}
}

var EmbeddedUser = genEmbeddedUser{}.WithTable(clause.CurrentTable)
