// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.
// Source checksum: eb3d4893af04499fb860dc6ef8e230970064ecf5726aa030bf4efc9b4e6e5030

package models

import (
	"strings"

	"gorm.io/cli/gorm/examples/models"
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm/clause"
)

type embeddedMetaRelationsFields struct {
	Pets *petSliceRelation
}

type embeddedMetaStructRelation struct {
	field.Struct[models.EmbeddedMeta]
	embeddedMetaRelationsFields
}

type embeddedMetaSliceRelation struct {
	field.Slice[models.EmbeddedMeta]
	embeddedMetaRelationsFields
}

func newEmbeddedMetaRelationsFields(prefix string, depth int) embeddedMetaRelationsFields {
	return embeddedMetaRelationsFields{
		Pets: newPetSliceRelation(strings.TrimPrefix(prefix+".Pets", "."), depth-1),
	}
}

func newEmbeddedMetaStructRelation(prefix string, depth int) *embeddedMetaStructRelation {
	rel := &embeddedMetaStructRelation{
		field.Struct[models.EmbeddedMeta]{}.WithName(prefix),
		embeddedMetaRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.embeddedMetaRelationsFields = newEmbeddedMetaRelationsFields(prefix, depth)
	return rel
}

func newEmbeddedMetaSliceRelation(prefix string, depth int) *embeddedMetaSliceRelation {
	rel := &embeddedMetaSliceRelation{
		field.Slice[models.EmbeddedMeta]{}.WithName(prefix),
		embeddedMetaRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.embeddedMetaRelationsFields = newEmbeddedMetaRelationsFields(prefix, depth)
	return rel
}

var EmbeddedMetaRelations = newEmbeddedMetaRelationsFields("", 4)

type genEmbeddedMeta struct {
	Code field.String
	Pets field.Slice[models.Pet]
}

func (g genEmbeddedMeta) WithTable(table string) genEmbeddedMeta {
	return genEmbeddedMeta{
		Code: field.String{}.WithColumn("code").WithTable(table),
		Pets: field.Slice[models.Pet]{}.WithName("Pets"),
	}
}

var EmbeddedMeta = genEmbeddedMeta{}.WithTable(clause.CurrentTable)

type embeddedAuditRelationsFields struct {
	Pets    *petSliceRelation
	Company field.Struct[models.Company]
}

type embeddedAuditStructRelation struct {
	field.Struct[models.EmbeddedAudit]
	embeddedAuditRelationsFields
}

type embeddedAuditSliceRelation struct {
	field.Slice[models.EmbeddedAudit]
	embeddedAuditRelationsFields
}

func newEmbeddedAuditRelationsFields(prefix string, depth int) embeddedAuditRelationsFields {
	return embeddedAuditRelationsFields{
		Pets:    newPetSliceRelation(strings.TrimPrefix(prefix+".Pets", "."), depth-1),
		Company: newCompanyStructRelation(strings.TrimPrefix(prefix+".Company", "."), depth-1),
	}
}

func newEmbeddedAuditStructRelation(prefix string, depth int) *embeddedAuditStructRelation {
	rel := &embeddedAuditStructRelation{
		field.Struct[models.EmbeddedAudit]{}.WithName(prefix),
		embeddedAuditRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.embeddedAuditRelationsFields = newEmbeddedAuditRelationsFields(prefix, depth)
	return rel
}

func newEmbeddedAuditSliceRelation(prefix string, depth int) *embeddedAuditSliceRelation {
	rel := &embeddedAuditSliceRelation{
		field.Slice[models.EmbeddedAudit]{}.WithName(prefix),
		embeddedAuditRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.embeddedAuditRelationsFields = newEmbeddedAuditRelationsFields(prefix, depth)
	return rel
}

var EmbeddedAuditRelations = newEmbeddedAuditRelationsFields("", 4)

type genEmbeddedAudit struct {
	Code    field.String
	Pets    field.Slice[models.Pet]
	Company field.Struct[models.Company]
}

func (g genEmbeddedAudit) WithTable(table string) genEmbeddedAudit {
	return genEmbeddedAudit{
		Code:    field.String{}.WithColumn("code").WithTable(table),
		Pets:    field.Slice[models.Pet]{}.WithName("Pets"),
		Company: field.Struct[models.Company]{}.WithName("Company"),
	}
}

var EmbeddedAudit = genEmbeddedAudit{}.WithTable(clause.CurrentTable)
