// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package models

import (
	"database/sql"

	"gorm.io/cli/gorm/examples"
	"gorm.io/cli/gorm/examples/models"
	"gorm.io/cli/gorm/examples/models/enum"
	enum2 "gorm.io/cli/gorm/examples/models/enum/enum"
	"gorm.io/cli/gorm/field"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

var User = struct {
	ID         field.Number[uint]
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field[gorm.DeletedAt]
	Name       field.String
	Age        field.Number[int]
	Birthday   field.Time
	Score      field.Field[sql.NullInt64]
	LastLogin  field.Time
	Account    field.Struct[models.Account]
	Pets       field.Slice[models.Pet]
	Toys       field.Slice[models.Toy]
	CompanyID  field.Number[int]
	Company    field.Struct[models.Company]
	ManagerID  field.Number[uint]
	Manager    field.Struct[models.User]
	Team       field.Slice[models.User]
	Languages  field.Slice[models.Language]
	Friends    field.Slice[models.User]
	Role       field.String
	IsAdult    field.Bool
	Profile    examples.JSON
	AwardTypes field.Struct[datatypes.JSONSlice[int]]
	TagTypes   field.Struct[datatypes.JSONSlice[models.UserTagType]]
	Tag        field.Field[models.UserTagType]
	Enum       field.Field[enum.Enum]
	Enum2      field.Field[enum2.Enum]
}{
	ID:         field.Number[uint]{}.WithColumn("id"),
	CreatedAt:  field.Time{}.WithColumn("created_at"),
	UpdatedAt:  field.Time{}.WithColumn("updated_at"),
	DeletedAt:  field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Name:       field.String{}.WithColumn("name"),
	Age:        field.Number[int]{}.WithColumn("age"),
	Birthday:   field.Time{}.WithColumn("birthday"),
	Score:      field.Field[sql.NullInt64]{}.WithColumn("score"),
	LastLogin:  field.Time{}.WithColumn("last_login"),
	Account:    field.Struct[models.Account]{}.WithName("Account"),
	Pets:       field.Slice[models.Pet]{}.WithName("Pets"),
	Toys:       field.Slice[models.Toy]{}.WithName("Toys"),
	CompanyID:  field.Number[int]{}.WithColumn("company_id"),
	Company:    field.Struct[models.Company]{}.WithName("Company"),
	ManagerID:  field.Number[uint]{}.WithColumn("manager_id"),
	Manager:    field.Struct[models.User]{}.WithName("Manager"),
	Team:       field.Slice[models.User]{}.WithName("Team"),
	Languages:  field.Slice[models.Language]{}.WithName("Languages"),
	Friends:    field.Slice[models.User]{}.WithName("Friends"),
	Role:       field.String{}.WithColumn("role"),
	IsAdult:    field.Bool{}.WithColumn("is_adult"),
	Profile:    examples.JSON{}.WithColumn("profile"),
	AwardTypes: field.Struct[datatypes.JSONSlice[int]]{}.WithName("AwardTypes"),
	TagTypes:   field.Struct[datatypes.JSONSlice[models.UserTagType]]{}.WithName("TagTypes"),
	Tag:        field.Field[models.UserTagType]{}.WithColumn("tag"),
	Enum:       field.Field[enum.Enum]{}.WithColumn("enum"),
	Enum2:      field.Field[enum2.Enum]{}.WithColumn("enum2"),
}

var UserRelations = struct {
	Account field.Struct[models.Account]
	Pets    struct {
		field.Slice[models.Pet]
		Toy field.Struct[models.Toy]
	}
	Toys    field.Slice[models.Toy]
	Company field.Struct[models.Company]
	Manager struct {
		field.Struct[models.User]
		Account field.Struct[models.Account]
		Pets    struct {
			field.Slice[models.Pet]
			Toy field.Struct[models.Toy]
		}
		Toys      field.Slice[models.Toy]
		Company   field.Struct[models.Company]
		Manager   field.Struct[models.User]
		Team      field.Slice[models.User]
		Languages field.Slice[models.Language]
		Friends   field.Slice[models.User]
	}
	Team struct {
		field.Slice[models.User]
		Account field.Struct[models.Account]
		Pets    struct {
			field.Slice[models.Pet]
			Toy field.Struct[models.Toy]
		}
		Toys      field.Slice[models.Toy]
		Company   field.Struct[models.Company]
		Manager   field.Struct[models.User]
		Team      field.Slice[models.User]
		Languages field.Slice[models.Language]
		Friends   field.Slice[models.User]
	}
	Languages field.Slice[models.Language]
	Friends   struct {
		field.Slice[models.User]
		Account field.Struct[models.Account]
		Pets    struct {
			field.Slice[models.Pet]
			Toy field.Struct[models.Toy]
		}
		Toys      field.Slice[models.Toy]
		Company   field.Struct[models.Company]
		Manager   field.Struct[models.User]
		Team      field.Slice[models.User]
		Languages field.Slice[models.Language]
		Friends   field.Slice[models.User]
	}
}{
	Account: field.Struct[models.Account]{}.WithName("Account"),
	Pets: struct {
		field.Slice[models.Pet]
		Toy field.Struct[models.Toy]
	}{
		field.Slice[models.Pet]{}.WithName("Pets"),
		field.Struct[models.Toy]{}.WithName("Pets.Toy"),
	},
	Toys:    field.Slice[models.Toy]{}.WithName("Toys"),
	Company: field.Struct[models.Company]{}.WithName("Company"),
	Manager: struct {
		field.Struct[models.User]
		Account field.Struct[models.Account]
		Pets    struct {
			field.Slice[models.Pet]
			Toy field.Struct[models.Toy]
		}
		Toys      field.Slice[models.Toy]
		Company   field.Struct[models.Company]
		Manager   field.Struct[models.User]
		Team      field.Slice[models.User]
		Languages field.Slice[models.Language]
		Friends   field.Slice[models.User]
	}{
		field.Struct[models.User]{}.WithName("Manager"),
		field.Struct[models.Account]{}.WithName("Manager.Account"),
		struct {
			field.Slice[models.Pet]
			Toy field.Struct[models.Toy]
		}{
			field.Slice[models.Pet]{}.WithName("Manager.Pets"),
			field.Struct[models.Toy]{}.WithName("Manager.Pets.Toy"),
		},
		field.Slice[models.Toy]{}.WithName("Manager.Toys"),
		field.Struct[models.Company]{}.WithName("Manager.Company"),
		field.Struct[models.User]{}.WithName("Manager.Manager"),
		field.Slice[models.User]{}.WithName("Manager.Team"),
		field.Slice[models.Language]{}.WithName("Manager.Languages"),
		field.Slice[models.User]{}.WithName("Manager.Friends"),
	},
	Team: struct {
		field.Slice[models.User]
		Account field.Struct[models.Account]
		Pets    struct {
			field.Slice[models.Pet]
			Toy field.Struct[models.Toy]
		}
		Toys      field.Slice[models.Toy]
		Company   field.Struct[models.Company]
		Manager   field.Struct[models.User]
		Team      field.Slice[models.User]
		Languages field.Slice[models.Language]
		Friends   field.Slice[models.User]
	}{
		field.Slice[models.User]{}.WithName("Team"),
		field.Struct[models.Account]{}.WithName("Team.Account"),
		struct {
			field.Slice[models.Pet]
			Toy field.Struct[models.Toy]
		}{
			field.Slice[models.Pet]{}.WithName("Team.Pets"),
			field.Struct[models.Toy]{}.WithName("Team.Pets.Toy"),
		},
		field.Slice[models.Toy]{}.WithName("Team.Toys"),
		field.Struct[models.Company]{}.WithName("Team.Company"),
		field.Struct[models.User]{}.WithName("Team.Manager"),
		field.Slice[models.User]{}.WithName("Team.Team"),
		field.Slice[models.Language]{}.WithName("Team.Languages"),
		field.Slice[models.User]{}.WithName("Team.Friends"),
	},
	Languages: field.Slice[models.Language]{}.WithName("Languages"),
	Friends: struct {
		field.Slice[models.User]
		Account field.Struct[models.Account]
		Pets    struct {
			field.Slice[models.Pet]
			Toy field.Struct[models.Toy]
		}
		Toys      field.Slice[models.Toy]
		Company   field.Struct[models.Company]
		Manager   field.Struct[models.User]
		Team      field.Slice[models.User]
		Languages field.Slice[models.Language]
		Friends   field.Slice[models.User]
	}{
		field.Slice[models.User]{}.WithName("Friends"),
		field.Struct[models.Account]{}.WithName("Friends.Account"),
		struct {
			field.Slice[models.Pet]
			Toy field.Struct[models.Toy]
		}{
			field.Slice[models.Pet]{}.WithName("Friends.Pets"),
			field.Struct[models.Toy]{}.WithName("Friends.Pets.Toy"),
		},
		field.Slice[models.Toy]{}.WithName("Friends.Toys"),
		field.Struct[models.Company]{}.WithName("Friends.Company"),
		field.Struct[models.User]{}.WithName("Friends.Manager"),
		field.Slice[models.User]{}.WithName("Friends.Team"),
		field.Slice[models.Language]{}.WithName("Friends.Languages"),
		field.Slice[models.User]{}.WithName("Friends.Friends"),
	},
}

var Account = struct {
	ID           field.Number[uint]
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field[gorm.DeletedAt]
	UserID       field.Field[sql.NullInt64]
	Number       field.String
	RewardPoints field.Field[sql.NullInt64]
	LastUsedAt   field.Time
}{
	ID:           field.Number[uint]{}.WithColumn("id"),
	CreatedAt:    field.Time{}.WithColumn("created_at"),
	UpdatedAt:    field.Time{}.WithColumn("updated_at"),
	DeletedAt:    field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	UserID:       field.Field[sql.NullInt64]{}.WithColumn("user_id"),
	Number:       field.String{}.WithColumn("number"),
	RewardPoints: field.Field[sql.NullInt64]{}.WithColumn("reward_points"),
	LastUsedAt:   field.Time{}.WithColumn("last_used_at"),
}

var Pet = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	UserID    field.Number[uint]
	Name      field.String
	Toy       field.Struct[models.Toy]
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	UserID:    field.Number[uint]{}.WithColumn("user_id"),
	Name:      field.String{}.WithColumn("name"),
	Toy:       field.Struct[models.Toy]{}.WithName("Toy"),
}

var PetRelations = struct {
	Toy field.Struct[models.Toy]
}{
	Toy: field.Struct[models.Toy]{}.WithName("Toy"),
}

var Toy = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	Name      field.String
	OwnerID   field.Number[uint]
	OwnerType field.String
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Name:      field.String{}.WithColumn("name"),
	OwnerID:   field.Number[uint]{}.WithColumn("owner_id"),
	OwnerType: field.String{}.WithColumn("owner_type"),
}

var Company = struct {
	ID   field.Number[int]
	Name field.String
}{
	ID:   field.Number[int]{}.WithColumn("id"),
	Name: field.String{}.WithColumn("name"),
}

var Language = struct {
	Code field.String
	Name field.String
}{
	Code: field.String{}.WithColumn("code"),
	Name: field.String{}.WithColumn("name"),
}

var CreditCard = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	Number    field.String
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Number:    field.String{}.WithColumn("number"),
}
