// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package models

import (
	"database/sql"
	"strings"

	"gorm.io/cli/gorm/examples"
	"gorm.io/cli/gorm/examples/models"
	"gorm.io/cli/gorm/examples/models/enum"
	enum2 "gorm.io/cli/gorm/examples/models/enum/enum"
	"gorm.io/cli/gorm/field"
	"gorm.io/datatypes"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type userRelationsFields struct {
	Account   field.Struct[models.Account]
	Pets      *petSliceRelation
	Toys      field.Slice[models.Toy]
	Company   field.Struct[models.Company]
	Manager   *userStructRelation
	Team      *userSliceRelation
	Languages field.Slice[models.Language]
	Friends   *userSliceRelation
}

type userStructRelation struct {
	field.Struct[models.User]
	userRelationsFields
}

type userSliceRelation struct {
	field.Slice[models.User]
	userRelationsFields
}

func newUserRelationsFields(prefix string, depth int) userRelationsFields {
	return userRelationsFields{
		Account:   newAccountStructRelation(strings.TrimPrefix(prefix+".Account", "."), depth-1),
		Pets:      newPetSliceRelation(strings.TrimPrefix(prefix+".Pets", "."), depth-1),
		Toys:      newToySliceRelation(strings.TrimPrefix(prefix+".Toys", "."), depth-1),
		Company:   newCompanyStructRelation(strings.TrimPrefix(prefix+".Company", "."), depth-1),
		Manager:   newUserStructRelation(strings.TrimPrefix(prefix+".Manager", "."), depth-1),
		Team:      newUserSliceRelation(strings.TrimPrefix(prefix+".Team", "."), depth-1),
		Languages: newLanguageSliceRelation(strings.TrimPrefix(prefix+".Languages", "."), depth-1),
		Friends:   newUserSliceRelation(strings.TrimPrefix(prefix+".Friends", "."), depth-1),
	}
}

func newUserStructRelation(prefix string, depth int) *userStructRelation {
	rel := &userStructRelation{
		field.Struct[models.User]{}.WithName(prefix),
		userRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.userRelationsFields = newUserRelationsFields(prefix, depth)
	return rel
}

func newUserSliceRelation(prefix string, depth int) *userSliceRelation {
	rel := &userSliceRelation{
		field.Slice[models.User]{}.WithName(prefix),
		userRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.userRelationsFields = newUserRelationsFields(prefix, depth)
	return rel
}

var UserRelations = newUserRelationsFields("", 4)

type genUser struct {
	ID         field.Number[uint]
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field[gorm.DeletedAt]
	Name       field.String
	Age        field.Number[int]
	Birthday   field.Time
	Score      field.Field[sql.NullInt64]
	LastLogin  field.Time
	Account    field.Struct[models.Account]
	Pets       field.Slice[models.Pet]
	Toys       field.Slice[models.Toy]
	CompanyID  field.Number[int]
	Company    field.Struct[models.Company]
	ManagerID  field.Number[uint]
	Manager    field.Struct[models.User]
	Team       field.Slice[models.User]
	Languages  field.Slice[models.Language]
	Friends    field.Slice[models.User]
	Role       field.String
	IsAdult    field.Bool
	Profile    examples.JSON
	AwardTypes field.Field[datatypes.JSONSlice[int]]
	TagTypes   field.Field[datatypes.JSONSlice[models.UserTagType]]
	Tag        field.Field[models.UserTagType]
	Enum       field.Field[enum.Enum]
	Enum2      field.Field[enum2.Enum]
}

func (g genUser) WithTable(table string) genUser {
	return genUser{
		ID:         field.Number[uint]{}.WithColumn("id").WithTable(table),
		CreatedAt:  field.Time{}.WithColumn("created_at").WithTable(table),
		UpdatedAt:  field.Time{}.WithColumn("updated_at").WithTable(table),
		DeletedAt:  field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at").WithTable(table),
		Name:       field.String{}.WithColumn("name").WithTable(table),
		Age:        field.Number[int]{}.WithColumn("age").WithTable(table),
		Birthday:   field.Time{}.WithColumn("birthday").WithTable(table),
		Score:      field.Field[sql.NullInt64]{}.WithColumn("score").WithTable(table),
		LastLogin:  field.Time{}.WithColumn("last_login").WithTable(table),
		Account:    field.Struct[models.Account]{}.WithName("Account"),
		Pets:       field.Slice[models.Pet]{}.WithName("Pets"),
		Toys:       field.Slice[models.Toy]{}.WithName("Toys"),
		CompanyID:  field.Number[int]{}.WithColumn("company_id").WithTable(table),
		Company:    field.Struct[models.Company]{}.WithName("Company"),
		ManagerID:  field.Number[uint]{}.WithColumn("manager_id").WithTable(table),
		Manager:    field.Struct[models.User]{}.WithName("Manager"),
		Team:       field.Slice[models.User]{}.WithName("Team"),
		Languages:  field.Slice[models.Language]{}.WithName("Languages"),
		Friends:    field.Slice[models.User]{}.WithName("Friends"),
		Role:       field.String{}.WithColumn("role").WithTable(table),
		IsAdult:    field.Bool{}.WithColumn("is_adult").WithTable(table),
		Profile:    examples.JSON{}.WithColumn("profile").WithTable(table),
		AwardTypes: field.Field[datatypes.JSONSlice[int]]{}.WithColumn("award_types").WithTable(table),
		TagTypes:   field.Field[datatypes.JSONSlice[models.UserTagType]]{}.WithColumn("tag_types").WithTable(table),
		Tag:        field.Field[models.UserTagType]{}.WithColumn("tag").WithTable(table),
		Enum:       field.Field[enum.Enum]{}.WithColumn("enum").WithTable(table),
		Enum2:      field.Field[enum2.Enum]{}.WithColumn("enum2").WithTable(table),
	}
}

var User = genUser{}.WithTable(clause.CurrentTable)

func newAccountStructRelation(prefix string, depth int) field.Struct[models.Account] {
	return field.Struct[models.Account]{}.WithName(prefix)
}

func newAccountSliceRelation(prefix string, depth int) field.Slice[models.Account] {
	return field.Slice[models.Account]{}.WithName(prefix)
}

type genAccount struct {
	ID           field.Number[uint]
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field[gorm.DeletedAt]
	UserID       field.Field[sql.NullInt64]
	Number       field.String
	RewardPoints field.Field[sql.NullInt64]
	LastUsedAt   field.Time
}

func (g genAccount) WithTable(table string) genAccount {
	return genAccount{
		ID:           field.Number[uint]{}.WithColumn("id").WithTable(table),
		CreatedAt:    field.Time{}.WithColumn("created_at").WithTable(table),
		UpdatedAt:    field.Time{}.WithColumn("updated_at").WithTable(table),
		DeletedAt:    field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at").WithTable(table),
		UserID:       field.Field[sql.NullInt64]{}.WithColumn("user_id").WithTable(table),
		Number:       field.String{}.WithColumn("number").WithTable(table),
		RewardPoints: field.Field[sql.NullInt64]{}.WithColumn("reward_points").WithTable(table),
		LastUsedAt:   field.Time{}.WithColumn("last_used_at").WithTable(table),
	}
}

var Account = genAccount{}.WithTable(clause.CurrentTable)

type petRelationsFields struct {
	Toy field.Struct[models.Toy]
}

type petStructRelation struct {
	field.Struct[models.Pet]
	petRelationsFields
}

type petSliceRelation struct {
	field.Slice[models.Pet]
	petRelationsFields
}

func newPetRelationsFields(prefix string, depth int) petRelationsFields {
	return petRelationsFields{
		Toy: newToyStructRelation(strings.TrimPrefix(prefix+".Toy", "."), depth-1),
	}
}

func newPetStructRelation(prefix string, depth int) *petStructRelation {
	rel := &petStructRelation{
		field.Struct[models.Pet]{}.WithName(prefix),
		petRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.petRelationsFields = newPetRelationsFields(prefix, depth)
	return rel
}

func newPetSliceRelation(prefix string, depth int) *petSliceRelation {
	rel := &petSliceRelation{
		field.Slice[models.Pet]{}.WithName(prefix),
		petRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.petRelationsFields = newPetRelationsFields(prefix, depth)
	return rel
}

var PetRelations = newPetRelationsFields("", 4)

type genPet struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	UserID    field.Number[uint]
	Name      field.String
	Toy       field.Struct[models.Toy]
}

func (g genPet) WithTable(table string) genPet {
	return genPet{
		ID:        field.Number[uint]{}.WithColumn("id").WithTable(table),
		CreatedAt: field.Time{}.WithColumn("created_at").WithTable(table),
		UpdatedAt: field.Time{}.WithColumn("updated_at").WithTable(table),
		DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at").WithTable(table),
		UserID:    field.Number[uint]{}.WithColumn("user_id").WithTable(table),
		Name:      field.String{}.WithColumn("name").WithTable(table),
		Toy:       field.Struct[models.Toy]{}.WithName("Toy"),
	}
}

var Pet = genPet{}.WithTable(clause.CurrentTable)

func newToyStructRelation(prefix string, depth int) field.Struct[models.Toy] {
	return field.Struct[models.Toy]{}.WithName(prefix)
}

func newToySliceRelation(prefix string, depth int) field.Slice[models.Toy] {
	return field.Slice[models.Toy]{}.WithName(prefix)
}

type genToy struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	Name      field.String
	OwnerID   field.Number[uint]
	OwnerType field.String
}

func (g genToy) WithTable(table string) genToy {
	return genToy{
		ID:        field.Number[uint]{}.WithColumn("id").WithTable(table),
		CreatedAt: field.Time{}.WithColumn("created_at").WithTable(table),
		UpdatedAt: field.Time{}.WithColumn("updated_at").WithTable(table),
		DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at").WithTable(table),
		Name:      field.String{}.WithColumn("name").WithTable(table),
		OwnerID:   field.Number[uint]{}.WithColumn("owner_id").WithTable(table),
		OwnerType: field.String{}.WithColumn("owner_type").WithTable(table),
	}
}

var Toy = genToy{}.WithTable(clause.CurrentTable)

func newCompanyStructRelation(prefix string, depth int) field.Struct[models.Company] {
	return field.Struct[models.Company]{}.WithName(prefix)
}

func newCompanySliceRelation(prefix string, depth int) field.Slice[models.Company] {
	return field.Slice[models.Company]{}.WithName(prefix)
}

type genCompany struct {
	ID   field.Number[int]
	Name field.String
}

func (g genCompany) WithTable(table string) genCompany {
	return genCompany{
		ID:   field.Number[int]{}.WithColumn("id").WithTable(table),
		Name: field.String{}.WithColumn("name").WithTable(table),
	}
}

var Company = genCompany{}.WithTable(clause.CurrentTable)

func newLanguageStructRelation(prefix string, depth int) field.Struct[models.Language] {
	return field.Struct[models.Language]{}.WithName(prefix)
}

func newLanguageSliceRelation(prefix string, depth int) field.Slice[models.Language] {
	return field.Slice[models.Language]{}.WithName(prefix)
}

type genLanguage struct {
	Code field.String
	Name field.String
}

func (g genLanguage) WithTable(table string) genLanguage {
	return genLanguage{
		Code: field.String{}.WithColumn("code").WithTable(table),
		Name: field.String{}.WithColumn("name").WithTable(table),
	}
}

var Language = genLanguage{}.WithTable(clause.CurrentTable)

func newCreditCardStructRelation(prefix string, depth int) field.Struct[models.CreditCard] {
	return field.Struct[models.CreditCard]{}.WithName(prefix)
}

func newCreditCardSliceRelation(prefix string, depth int) field.Slice[models.CreditCard] {
	return field.Slice[models.CreditCard]{}.WithName(prefix)
}

type genCreditCard struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	Number    field.String
}

func (g genCreditCard) WithTable(table string) genCreditCard {
	return genCreditCard{
		ID:        field.Number[uint]{}.WithColumn("id").WithTable(table),
		CreatedAt: field.Time{}.WithColumn("created_at").WithTable(table),
		UpdatedAt: field.Time{}.WithColumn("updated_at").WithTable(table),
		DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at").WithTable(table),
		Number:    field.String{}.WithColumn("number").WithTable(table),
	}
}

var CreditCard = genCreditCard{}.WithTable(clause.CurrentTable)
