// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.
// Generation checksum: 135cd9386616b3e92552631cc062674d1d6a3f10bb80fd7f7033e251a6e2e387

package models

import (
	"strings"

	"gorm.io/cli/gorm/examples/models"
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm/clause"
)

type embeddedUserRelationsFields struct {
	Pets    *petSliceRelation
	Company field.Struct[models.Company]
}

type embeddedUserStructRelation struct {
	field.Struct[models.EmbeddedUser]
	embeddedUserRelationsFields
}

type embeddedUserSliceRelation struct {
	field.Slice[models.EmbeddedUser]
	embeddedUserRelationsFields
}

func newEmbeddedUserRelationsFields(prefix string, depth int) embeddedUserRelationsFields {
	return embeddedUserRelationsFields{
		Pets:    newPetSliceRelation(strings.TrimPrefix(prefix+".Pets", "."), depth-1),
		Company: newCompanyStructRelation(strings.TrimPrefix(prefix+".Company", "."), depth-1),
	}
}

func newEmbeddedUserStructRelation(prefix string, depth int) *embeddedUserStructRelation {
	rel := &embeddedUserStructRelation{
		field.Struct[models.EmbeddedUser]{}.WithName(prefix),
		embeddedUserRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.embeddedUserRelationsFields = newEmbeddedUserRelationsFields(prefix, depth)
	return rel
}

func newEmbeddedUserSliceRelation(prefix string, depth int) *embeddedUserSliceRelation {
	rel := &embeddedUserSliceRelation{
		field.Slice[models.EmbeddedUser]{}.WithName(prefix),
		embeddedUserRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.embeddedUserRelationsFields = newEmbeddedUserRelationsFields(prefix, depth)
	return rel
}

var EmbeddedUserRelations = newEmbeddedUserRelationsFields("", 4)

type genEmbeddedUser struct {
	Code    field.String
	Pets    field.Slice[models.Pet]
	Company field.Struct[models.Company]
	Name    field.String
}

func (g genEmbeddedUser) WithTable(table string) genEmbeddedUser {
	return genEmbeddedUser{
		Code:    field.String{}.WithColumn("code").WithTable(table),
		Pets:    field.Slice[models.Pet]{}.WithName("Pets"),
		Company: field.Struct[models.Company]{}.WithName("Company"),
		Name:    field.String{}.WithColumn("name").WithTable(table),
	}
}

var EmbeddedUser = genEmbeddedUser{}.WithTable(clause.CurrentTable)

type taggedEmbeddedUserRelationsFields struct {
	FilterPets    *petSliceRelation
	FilterCompany field.Struct[models.Company]
}

type taggedEmbeddedUserStructRelation struct {
	field.Struct[models.TaggedEmbeddedUser]
	taggedEmbeddedUserRelationsFields
}

type taggedEmbeddedUserSliceRelation struct {
	field.Slice[models.TaggedEmbeddedUser]
	taggedEmbeddedUserRelationsFields
}

func newTaggedEmbeddedUserRelationsFields(prefix string, depth int) taggedEmbeddedUserRelationsFields {
	return taggedEmbeddedUserRelationsFields{
		FilterPets:    newPetSliceRelation(strings.TrimPrefix(prefix+".FilterPets", "."), depth-1),
		FilterCompany: newCompanyStructRelation(strings.TrimPrefix(prefix+".FilterCompany", "."), depth-1),
	}
}

func newTaggedEmbeddedUserStructRelation(prefix string, depth int) *taggedEmbeddedUserStructRelation {
	rel := &taggedEmbeddedUserStructRelation{
		field.Struct[models.TaggedEmbeddedUser]{}.WithName(prefix),
		taggedEmbeddedUserRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.taggedEmbeddedUserRelationsFields = newTaggedEmbeddedUserRelationsFields(prefix, depth)
	return rel
}

func newTaggedEmbeddedUserSliceRelation(prefix string, depth int) *taggedEmbeddedUserSliceRelation {
	rel := &taggedEmbeddedUserSliceRelation{
		field.Slice[models.TaggedEmbeddedUser]{}.WithName(prefix),
		taggedEmbeddedUserRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.taggedEmbeddedUserRelationsFields = newTaggedEmbeddedUserRelationsFields(prefix, depth)
	return rel
}

var TaggedEmbeddedUserRelations = newTaggedEmbeddedUserRelationsFields("", 4)

type genTaggedEmbeddedUser struct {
	FilterCode    field.String
	FilterPets    field.Slice[models.Pet]
	FilterCompany field.Struct[models.Company]
	Name          field.String
}

func (g genTaggedEmbeddedUser) WithTable(table string) genTaggedEmbeddedUser {
	return genTaggedEmbeddedUser{
		FilterCode:    field.String{}.WithColumn("filter_code").WithTable(table),
		FilterPets:    field.Slice[models.Pet]{}.WithName("FilterPets"),
		FilterCompany: field.Struct[models.Company]{}.WithName("FilterCompany"),
		Name:          field.String{}.WithColumn("name").WithTable(table),
	}
}

var TaggedEmbeddedUser = genTaggedEmbeddedUser{}.WithTable(clause.CurrentTable)
