// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package models

import (
	"strings"

	"gorm.io/cli/gorm/examples/models"
	"gorm.io/cli/gorm/field"
)

type embeddedUserRelationsFields struct {
	Pets    *petSliceRelation
	Company field.Struct[models.Company]
}

type embeddedUserStructRelation struct {
	field.Struct[models.EmbeddedUser]
	embeddedUserRelationsFields
}

type embeddedUserSliceRelation struct {
	field.Slice[models.EmbeddedUser]
	embeddedUserRelationsFields
}

func newEmbeddedUserRelationsFields(prefix string, depth int) embeddedUserRelationsFields {
	return embeddedUserRelationsFields{
		Pets:    newPetSliceRelation(strings.TrimPrefix(prefix+".Pets", "."), depth-1),
		Company: newCompanyStructRelation(strings.TrimPrefix(prefix+".Company", "."), depth-1),
	}
}

func newEmbeddedUserStructRelation(prefix string, depth int) *embeddedUserStructRelation {
	rel := &embeddedUserStructRelation{
		field.Struct[models.EmbeddedUser]{}.WithName(prefix),
		embeddedUserRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.embeddedUserRelationsFields = newEmbeddedUserRelationsFields(prefix, depth)
	return rel
}

func newEmbeddedUserSliceRelation(prefix string, depth int) *embeddedUserSliceRelation {
	rel := &embeddedUserSliceRelation{
		field.Slice[models.EmbeddedUser]{}.WithName(prefix),
		embeddedUserRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.embeddedUserRelationsFields = newEmbeddedUserRelationsFields(prefix, depth)
	return rel
}

var EmbeddedUserRelations = newEmbeddedUserRelationsFields("", 4)

var EmbeddedUser = struct {
	Code    field.String
	Pets    field.Slice[models.Pet]
	Company field.Struct[models.Company]
	Name    field.String
}{
	Code:    field.String{}.WithColumn("code"),
	Pets:    field.Slice[models.Pet]{}.WithName("Pets"),
	Company: field.Struct[models.Company]{}.WithName("Company"),
	Name:    field.String{}.WithColumn("name"),
}
