// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package models

import (
	"database/sql"
	"strings"

	"gorm.io/cli/gorm/examples"
	"gorm.io/cli/gorm/examples/models"
	"gorm.io/cli/gorm/examples/models/enum"
	enum2 "gorm.io/cli/gorm/examples/models/enum/enum"
	"gorm.io/cli/gorm/field"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

func joinRelationPath(prefix, name string) string {
	if prefix == "" {
		return name
	}
	var b strings.Builder
	b.Grow(len(prefix) + len(name) + 1)
	b.WriteString(prefix)
	b.WriteByte('.')
	b.WriteString(name)
	return b.String()
}

type userRelationsFields struct {
	Account   *accountStructRelation
	Pets      *petSliceRelation
	Toys      *toySliceRelation
	Company   *companyStructRelation
	Manager   *userStructRelation
	Team      *userSliceRelation
	Languages *languageSliceRelation
	Friends   *userSliceRelation
}

type userStructRelation struct {
	field.Struct[models.User]
	userRelationsFields
}

type userSliceRelation struct {
	field.Slice[models.User]
	userRelationsFields
}

func newUserRelationsFields(prefix string, depth int) userRelationsFields {
	return userRelationsFields{
		Account:   newAccountStructRelation(joinRelationPath(prefix, "Account"), depth-1),
		Pets:      newPetSliceRelation(joinRelationPath(prefix, "Pets"), depth-1),
		Toys:      newToySliceRelation(joinRelationPath(prefix, "Toys"), depth-1),
		Company:   newCompanyStructRelation(joinRelationPath(prefix, "Company"), depth-1),
		Manager:   newUserStructRelation(joinRelationPath(prefix, "Manager"), depth-1),
		Team:      newUserSliceRelation(joinRelationPath(prefix, "Team"), depth-1),
		Languages: newLanguageSliceRelation(joinRelationPath(prefix, "Languages"), depth-1),
		Friends:   newUserSliceRelation(joinRelationPath(prefix, "Friends"), depth-1),
	}
}

func newUserStructRelation(prefix string, depth int) *userStructRelation {
	rel := &userStructRelation{
		field.Struct[models.User]{}.WithName(prefix),
		userRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.userRelationsFields = newUserRelationsFields(prefix, depth)
	return rel
}

func newUserSliceRelation(prefix string, depth int) *userSliceRelation {
	rel := &userSliceRelation{
		field.Slice[models.User]{}.WithName(prefix),
		userRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.userRelationsFields = newUserRelationsFields(prefix, depth)
	return rel
}

var UserRelations = newUserRelationsFields("", 4)

var User = struct {
	ID         field.Number[uint]
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field[gorm.DeletedAt]
	Name       field.String
	Age        field.Number[int]
	Birthday   field.Time
	Score      field.Field[sql.NullInt64]
	LastLogin  field.Time
	Account    field.Struct[models.Account]
	Pets       field.Slice[models.Pet]
	Toys       field.Slice[models.Toy]
	CompanyID  field.Number[int]
	Company    field.Struct[models.Company]
	ManagerID  field.Number[uint]
	Manager    field.Struct[models.User]
	Team       field.Slice[models.User]
	Languages  field.Slice[models.Language]
	Friends    field.Slice[models.User]
	Role       field.String
	IsAdult    field.Bool
	Profile    examples.JSON
	AwardTypes field.Struct[datatypes.JSONSlice[int]]
	TagTypes   field.Struct[datatypes.JSONSlice[models.UserTagType]]
	Tag        field.Field[models.UserTagType]
	Enum       field.Field[enum.Enum]
	Enum2      field.Field[enum2.Enum]
}{
	ID:         field.Number[uint]{}.WithColumn("id"),
	CreatedAt:  field.Time{}.WithColumn("created_at"),
	UpdatedAt:  field.Time{}.WithColumn("updated_at"),
	DeletedAt:  field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Name:       field.String{}.WithColumn("name"),
	Age:        field.Number[int]{}.WithColumn("age"),
	Birthday:   field.Time{}.WithColumn("birthday"),
	Score:      field.Field[sql.NullInt64]{}.WithColumn("score"),
	LastLogin:  field.Time{}.WithColumn("last_login"),
	Account:    field.Struct[models.Account]{}.WithName("Account"),
	Pets:       field.Slice[models.Pet]{}.WithName("Pets"),
	Toys:       field.Slice[models.Toy]{}.WithName("Toys"),
	CompanyID:  field.Number[int]{}.WithColumn("company_id"),
	Company:    field.Struct[models.Company]{}.WithName("Company"),
	ManagerID:  field.Number[uint]{}.WithColumn("manager_id"),
	Manager:    field.Struct[models.User]{}.WithName("Manager"),
	Team:       field.Slice[models.User]{}.WithName("Team"),
	Languages:  field.Slice[models.Language]{}.WithName("Languages"),
	Friends:    field.Slice[models.User]{}.WithName("Friends"),
	Role:       field.String{}.WithColumn("role"),
	IsAdult:    field.Bool{}.WithColumn("is_adult"),
	Profile:    examples.JSON{}.WithColumn("profile"),
	AwardTypes: field.Struct[datatypes.JSONSlice[int]]{}.WithName("AwardTypes"),
	TagTypes:   field.Struct[datatypes.JSONSlice[models.UserTagType]]{}.WithName("TagTypes"),
	Tag:        field.Field[models.UserTagType]{}.WithColumn("tag"),
	Enum:       field.Field[enum.Enum]{}.WithColumn("enum"),
	Enum2:      field.Field[enum2.Enum]{}.WithColumn("enum2"),
}

type accountRelationsFields struct {
}

type accountStructRelation struct {
	field.Struct[models.Account]
	accountRelationsFields
}

type accountSliceRelation struct {
	field.Slice[models.Account]
	accountRelationsFields
}

func newAccountRelationsFields(prefix string, depth int) accountRelationsFields {
	return accountRelationsFields{}
}

func newAccountStructRelation(prefix string, depth int) *accountStructRelation {
	rel := &accountStructRelation{
		field.Struct[models.Account]{}.WithName(prefix),
		accountRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.accountRelationsFields = newAccountRelationsFields(prefix, depth)
	return rel
}

func newAccountSliceRelation(prefix string, depth int) *accountSliceRelation {
	rel := &accountSliceRelation{
		field.Slice[models.Account]{}.WithName(prefix),
		accountRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.accountRelationsFields = newAccountRelationsFields(prefix, depth)
	return rel
}

var Account = struct {
	ID           field.Number[uint]
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field[gorm.DeletedAt]
	UserID       field.Field[sql.NullInt64]
	Number       field.String
	RewardPoints field.Field[sql.NullInt64]
	LastUsedAt   field.Time
}{
	ID:           field.Number[uint]{}.WithColumn("id"),
	CreatedAt:    field.Time{}.WithColumn("created_at"),
	UpdatedAt:    field.Time{}.WithColumn("updated_at"),
	DeletedAt:    field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	UserID:       field.Field[sql.NullInt64]{}.WithColumn("user_id"),
	Number:       field.String{}.WithColumn("number"),
	RewardPoints: field.Field[sql.NullInt64]{}.WithColumn("reward_points"),
	LastUsedAt:   field.Time{}.WithColumn("last_used_at"),
}

type petRelationsFields struct {
	Toy *toyStructRelation
}

type petStructRelation struct {
	field.Struct[models.Pet]
	petRelationsFields
}

type petSliceRelation struct {
	field.Slice[models.Pet]
	petRelationsFields
}

func newPetRelationsFields(prefix string, depth int) petRelationsFields {
	return petRelationsFields{
		Toy: newToyStructRelation(joinRelationPath(prefix, "Toy"), depth-1),
	}
}

func newPetStructRelation(prefix string, depth int) *petStructRelation {
	rel := &petStructRelation{
		field.Struct[models.Pet]{}.WithName(prefix),
		petRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.petRelationsFields = newPetRelationsFields(prefix, depth)
	return rel
}

func newPetSliceRelation(prefix string, depth int) *petSliceRelation {
	rel := &petSliceRelation{
		field.Slice[models.Pet]{}.WithName(prefix),
		petRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.petRelationsFields = newPetRelationsFields(prefix, depth)
	return rel
}

var PetRelations = newPetRelationsFields("", 4)

var Pet = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	UserID    field.Number[uint]
	Name      field.String
	Toy       field.Struct[models.Toy]
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	UserID:    field.Number[uint]{}.WithColumn("user_id"),
	Name:      field.String{}.WithColumn("name"),
	Toy:       field.Struct[models.Toy]{}.WithName("Toy"),
}

type toyRelationsFields struct {
}

type toyStructRelation struct {
	field.Struct[models.Toy]
	toyRelationsFields
}

type toySliceRelation struct {
	field.Slice[models.Toy]
	toyRelationsFields
}

func newToyRelationsFields(prefix string, depth int) toyRelationsFields {
	return toyRelationsFields{}
}

func newToyStructRelation(prefix string, depth int) *toyStructRelation {
	rel := &toyStructRelation{
		field.Struct[models.Toy]{}.WithName(prefix),
		toyRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.toyRelationsFields = newToyRelationsFields(prefix, depth)
	return rel
}

func newToySliceRelation(prefix string, depth int) *toySliceRelation {
	rel := &toySliceRelation{
		field.Slice[models.Toy]{}.WithName(prefix),
		toyRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.toyRelationsFields = newToyRelationsFields(prefix, depth)
	return rel
}

var Toy = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	Name      field.String
	OwnerID   field.Number[uint]
	OwnerType field.String
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Name:      field.String{}.WithColumn("name"),
	OwnerID:   field.Number[uint]{}.WithColumn("owner_id"),
	OwnerType: field.String{}.WithColumn("owner_type"),
}

type companyRelationsFields struct {
}

type companyStructRelation struct {
	field.Struct[models.Company]
	companyRelationsFields
}

type companySliceRelation struct {
	field.Slice[models.Company]
	companyRelationsFields
}

func newCompanyRelationsFields(prefix string, depth int) companyRelationsFields {
	return companyRelationsFields{}
}

func newCompanyStructRelation(prefix string, depth int) *companyStructRelation {
	rel := &companyStructRelation{
		field.Struct[models.Company]{}.WithName(prefix),
		companyRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.companyRelationsFields = newCompanyRelationsFields(prefix, depth)
	return rel
}

func newCompanySliceRelation(prefix string, depth int) *companySliceRelation {
	rel := &companySliceRelation{
		field.Slice[models.Company]{}.WithName(prefix),
		companyRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.companyRelationsFields = newCompanyRelationsFields(prefix, depth)
	return rel
}

var Company = struct {
	ID   field.Number[int]
	Name field.String
}{
	ID:   field.Number[int]{}.WithColumn("id"),
	Name: field.String{}.WithColumn("name"),
}

type languageRelationsFields struct {
}

type languageStructRelation struct {
	field.Struct[models.Language]
	languageRelationsFields
}

type languageSliceRelation struct {
	field.Slice[models.Language]
	languageRelationsFields
}

func newLanguageRelationsFields(prefix string, depth int) languageRelationsFields {
	return languageRelationsFields{}
}

func newLanguageStructRelation(prefix string, depth int) *languageStructRelation {
	rel := &languageStructRelation{
		field.Struct[models.Language]{}.WithName(prefix),
		languageRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.languageRelationsFields = newLanguageRelationsFields(prefix, depth)
	return rel
}

func newLanguageSliceRelation(prefix string, depth int) *languageSliceRelation {
	rel := &languageSliceRelation{
		field.Slice[models.Language]{}.WithName(prefix),
		languageRelationsFields{},
	}
	if depth <= 0 {
		return rel
	}
	rel.languageRelationsFields = newLanguageRelationsFields(prefix, depth)
	return rel
}

var Language = struct {
	Code field.String
	Name field.String
}{
	Code: field.String{}.WithColumn("code"),
	Name: field.String{}.WithColumn("name"),
}

var CreditCard = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	Number    field.String
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Number:    field.String{}.WithColumn("number"),
}
