// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.
// Generation checksum: 49f39540c0ae5b0d814556cc54ebe05e6f10a1182810c4c260cb6e3a56ca5b31

package nested

import (
	"gorm.io/cli/gorm/examples/filters/twolevel/nested"
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm/clause"
)

func newS1StructRelation(prefix string, depth int) field.Struct[nested.S1] {
	return field.Struct[nested.S1]{}.WithName(prefix)
}

func newS1SliceRelation(prefix string, depth int) field.Slice[nested.S1] {
	return field.Slice[nested.S1]{}.WithName(prefix)
}

type genS1 struct {
	ID field.Number[int]
}

func (g genS1) WithTable(table string) genS1 {
	return genS1{
		ID: field.Number[int]{}.WithColumn("id").WithTable(table),
	}
}

var S1 = genS1{}.WithTable(clause.CurrentTable)
