// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.
// Source checksum: 8c41fef04a71a0301e32efaf76d5cdbaa4e6aebd0b4ffe54e9368561be5da2db

package blacklist

import (
	"gorm.io/cli/gorm/examples/filters/blacklist"
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm/clause"
)

func newS1StructRelation(prefix string, depth int) field.Struct[blacklist.S1] {
	return field.Struct[blacklist.S1]{}.WithName(prefix)
}

func newS1SliceRelation(prefix string, depth int) field.Slice[blacklist.S1] {
	return field.Slice[blacklist.S1]{}.WithName(prefix)
}

type genS1 struct {
	ID   field.Number[int]
	Name field.String
}

func (g genS1) WithTable(table string) genS1 {
	return genS1{
		ID:   field.Number[int]{}.WithColumn("id").WithTable(table),
		Name: field.String{}.WithColumn("name").WithTable(table),
	}
}

var S1 = genS1{}.WithTable(clause.CurrentTable)
